config/routes.rb
Rails.application.routes.draw do
  resources :providers
  resources :places
  resources :credit_cards
  resources :clients

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :creditCard
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:latitude, :longitude, :name, :age, :rate, :address, :paymentMethods, :value, :attendedPlaces, :operatingDateTime, :description, :creditCard_id, :weeklyViews, :monthlyViews, :weeklyContacts, :monthlyContacts)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.number_field :latitude, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.number_field :longitude, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.number_field :rate %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :paymentMethods %><br>
    <%= f.text_field :paymentMethods %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :attendedPlaces %><br>
    <%= f.text_field :attendedPlaces %>
  </div>
  <div class="field">
    <%= f.label :operatingDateTime %><br>
    <%= f.text_field :operatingDateTime %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :creditCard_id %><br>
    <%= f.collection_select(:creditCard_id, CreditCard.all, :id, :ownerName) %>
  </div>
  <div class="field">
    <%= f.label :weeklyViews %><br>
    <%= f.number_field :weeklyViews %>
  </div>
  <div class="field">
    <%= f.label :monthlyViews %><br>
    <%= f.number_field :monthlyViews %>
  </div>
  <div class="field">
    <%= f.label :weeklyContacts %><br>
    <%= f.number_field :weeklyContacts %>
  </div>
  <div class="field">
    <%= f.label :monthlyContacts %><br>
    <%= f.number_field :monthlyContacts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Providers</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>Age</th>
      <th>Rate</th>
      <th>Address</th>
      <th>Paymentmethods</th>
      <th>Value</th>
      <th>Attendedplaces</th>
      <th>Operatingdatetime</th>
      <th>Description</th>
      <th>Creditcard</th>
      <th>Weeklyviews</th>
      <th>Monthlyviews</th>
      <th>Weeklycontacts</th>
      <th>Monthlycontacts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.latitude %></td>
        <td><%= provider.longitude %></td>
        <td><%= provider.name %></td>
        <td><%= provider.age %></td>
        <td><%= provider.rate %></td>
        <td><%= provider.address %></td>
        <td><%= provider.paymentMethods %></td>
        <td><%= provider.value %></td>
        <td><%= provider.attendedPlaces %></td>
        <td><%= provider.operatingDateTime %></td>
        <td><%= provider.description %></td>
        <td><%= provider.creditCard.ownerName %></td>
        <td><%= provider.weeklyViews %></td>
        <td><%= provider.monthlyViews %></td>
        <td><%= provider.weeklyContacts %></td>
        <td><%= provider.monthlyContacts %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @provider.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @provider.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @provider.age %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @provider.rate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @provider.address %>
</p>

<p>
  <strong>Paymentmethods:</strong>
  <%= @provider.paymentMethods %>
</p>

<p>
  <strong>Value:</strong>
  <%= @provider.value %>
</p>

<p>
  <strong>Attendedplaces:</strong>
  <%= @provider.attendedPlaces %>
</p>

<p>
  <strong>Operatingdatetime:</strong>
  <%= @provider.operatingDateTime %>
</p>

<p>
  <strong>Description:</strong>
  <%= @provider.description %>
</p>

<p>
  <strong>Creditcard:</strong>
  <%= @provider.creditCard.ownerName %>
</p>

<p>
  <strong>Weeklyviews:</strong>
  <%= @provider.weeklyViews %>
</p>

<p>
  <strong>Monthlyviews:</strong>
  <%= @provider.monthlyViews %>
</p>

<p>
  <strong>Weeklycontacts:</strong>
  <%= @provider.weeklyContacts %>
</p>

<p>
  <strong>Monthlycontacts:</strong>
  <%= @provider.monthlyContacts %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>