config/routes.rb
Rails.application.routes.draw do
  resources :providers
  resources :places
  resources :credit_cards
  resources :clients

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:cardNumber, :expirationMonth, :expirationYear, :securityCode, :ownerName, :creditCardFlag)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cardNumber %><br>
    <%= f.text_field :cardNumber %>
  </div>
  <div class="field">
    <%= f.label :expirationMonth %><br>
    <%= f.number_field :expirationMonth %>
  </div>
  <div class="field">
    <%= f.label :expirationYear %><br>
    <%= f.number_field :expirationYear %>
  </div>
  <div class="field">
    <%= f.label :securityCode %><br>
    <%= f.number_field :securityCode %>
  </div>
  <div class="field">
    <%= f.label :ownerName %><br>
    <%= f.text_field :ownerName %>
  </div>
  <div class="field">
    <%= f.label :creditCardFlag %><br>
    <%= f.text_field :creditCardFlag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing Credit Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Credit Cards</h1>

<table>
  <thead>
    <tr>
      <th>Cardnumber</th>
      <th>Expirationmonth</th>
      <th>Expirationyear</th>
      <th>Securitycode</th>
      <th>Ownername</th>
      <th>Creditcardflag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.cardNumber %></td>
        <td><%= credit_card.expirationMonth %></td>
        <td><%= credit_card.expirationYear %></td>
        <td><%= credit_card.securityCode %></td>
        <td><%= credit_card.ownerName %></td>
        <td><%= credit_card.creditCardFlag %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New Credit Card</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cardnumber:</strong>
  <%= @credit_card.cardNumber %>
</p>

<p>
  <strong>Expirationmonth:</strong>
  <%= @credit_card.expirationMonth %>
</p>

<p>
  <strong>Expirationyear:</strong>
  <%= @credit_card.expirationYear %>
</p>

<p>
  <strong>Securitycode:</strong>
  <%= @credit_card.securityCode %>
</p>

<p>
  <strong>Ownername:</strong>
  <%= @credit_card.ownerName %>
</p>

<p>
  <strong>Creditcardflag:</strong>
  <%= @credit_card.creditCardFlag %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>