config/routes.rb
Rails.application.routes.draw do
  resources :providers
  resources :places
  resources :credit_cards
  resources :clients

end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :creditCard
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:latitude, :longitude, :name, :rate, :address, :couver, :paymentMethods, :averageValue, :operatingDateTime, :agendaDescription, :weeklyViews, :monthlyViews, :creditCard_id)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.number_field :latitude, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.number_field :longitude, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.number_field :rate %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :couver %><br>
    <%= f.text_field :couver %>
  </div>
  <div class="field">
    <%= f.label :paymentMethods %><br>
    <%= f.text_field :paymentMethods %>
  </div>
  <div class="field">
    <%= f.label :averageValue %><br>
    <%= f.text_field :averageValue %>
  </div>
  <div class="field">
    <%= f.label :operatingDateTime %><br>
    <%= f.text_field :operatingDateTime %>
  </div>
  <div class="field">
    <%= f.label :agendaDescription %><br>
    <%= f.text_field :agendaDescription %>
  </div>
  <div class="field">
    <%= f.label :weeklyViews %><br>
    <%= f.number_field :weeklyViews %>
  </div>
  <div class="field">
    <%= f.label :monthlyViews %><br>
    <%= f.number_field :monthlyViews %>
  </div>
  <div class="field">
    <%= f.label :creditCard_id %><br>
    <%= f.collection_select(:creditCard_id, CreditCard.all, :id, :ownerName) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>Rate</th>
      <th>Address</th>
      <th>Couver</th>
      <th>Paymentmethods</th>
      <th>Averagevalue</th>
      <th>Operatingdatetime</th>
      <th>Agendadescription</th>
      <th>Weeklyviews</th>
      <th>Monthlyviews</th>
      <th>Creditcard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= place.name %></td>
        <td><%= place.rate %></td>
        <td><%= place.address %></td>
        <td><%= place.couver %></td>
        <td><%= place.paymentMethods %></td>
        <td><%= place.averageValue %></td>
        <td><%= place.operatingDateTime %></td>
        <td><%= place.agendaDescription %></td>
        <td><%= place.weeklyViews %></td>
        <td><%= place.monthlyViews %></td>
        <td><%= place.creditCard.ownerName %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @place.rate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Couver:</strong>
  <%= @place.couver %>
</p>

<p>
  <strong>Paymentmethods:</strong>
  <%= @place.paymentMethods %>
</p>

<p>
  <strong>Averagevalue:</strong>
  <%= @place.averageValue %>
</p>

<p>
  <strong>Operatingdatetime:</strong>
  <%= @place.operatingDateTime %>
</p>

<p>
  <strong>Agendadescription:</strong>
  <%= @place.agendaDescription %>
</p>

<p>
  <strong>Weeklyviews:</strong>
  <%= @place.weeklyViews %>
</p>

<p>
  <strong>Monthlyviews:</strong>
  <%= @place.monthlyViews %>
</p>

<p>
  <strong>Creditcard:</strong>
  <%= @place.creditCard.ownerName %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>